recipes/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^rest/', include('recipes_rest.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^recipes/', include('recipes_site.urls')),
]

recipes_site/urls.py
from django.conf.urls import url
from rest_framework_jwt.views import obtain_jwt_token

from . import views


app_name="recipes_site"
urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^$', views.index, name='index'),
    url(r'^(?P<recipe_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^instructions/(?P<moment_id>[0-9]+)/$', views.instructions, name='instructions'),
    url(r'^addrecipe/$', views.create_recipe, name='add-recipe'),
    url(r'^addquantity/$', views.create_quantity, name='add-quantity'),
    url(r'^addmoment/$', views.create_moment, name='add-moment'),
]

recipes_site/models.py
from django.db import models

# Create your models here.

recipes_site/forms.py
from django.forms import ModelForm
from django import forms
from recipes_models.models import Recipe, Moment, Quantity, Ingredient
from itertools import chain


class RecipeForm(ModelForm):

    source = forms.CharField()

    def __init__(self, time_units, categories):
        super().__init__()
        self.time_unit = forms.ChoiceField()
        self.time_unit.widget = forms.Select(choices=time_units)
        self.category = forms.ChoiceField()
        self.category.widget = forms.SelectMultiple(choices=categories)

    class Meta:
        model = Recipe
        exclude = ('creator',)


class MomentForm(ModelForm):

    def __init__(self, ingredients):
        self.extra_ingredients = forms.ChoiceField()
        self.extra_ingredients.widget = forms.SelectMultiple(choices=ingredients)
        super().__init__()

    class Meta:
        model = Moment
        exclude = ('recipe','ingredients')


class QuantityForm(ModelForm):

    amount = forms.IntegerField()
    amount.widget = forms.NumberInput(attrs={'name':'amount'})

    unit = forms.CharField()
    unit.widget = forms.TextInput(attrs={'name':'unit'})

    comment = forms.CharField()
    comment.widget = forms.TextInput(attrs={'name':'comment'})

    def __init__(self, ingredients):
        settings = {'data-placeholder':'Choose an ingredient','class':'chosen-select',}
        self.ingredient = forms.ChoiceField()
        self.ingredient.widget = forms.Select(choices=ingredients,
                                     attrs=settings)

        super().__init__()

    class Meta:
        model = Quantity
        fields = ('amount','unit','ingredient','comment',)

recipes_site/views.py
from django.shortcuts import render, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseForbidden

from .auth import JWTAuth

import requests

from .forms import *


@csrf_exempt
def index(request):
    token = request.COOKIES.get('token')
    if not token:
        return login(request)
    recipe_get = requests.get(
        "http://localhost:8000/rest/recipes/", auth=JWTAuth(token))
    if recipe_get.status_code >= 400:
        return login(request)
    return render(request, 'recipes_site/index.html', {'recipes': recipe_get.json()})


@csrf_exempt
def detail(request, recipe_id):
    token = request.COOKIES.get('token')
    if not token:
        return login(request)
    recipe_get = requests.get(
        "http://localhost:8000/rest/recipes/" + recipe_id + "/", auth=JWTAuth(token))
    if recipe_get.status_code >= 400:
        return login(request)
    recipe = recipe_get.json()
    parameters = {'recipe': recipe,
                  'moment': recipe["moments"][0]}
    return render(request, 'recipes_site/detail.html', parameters)


@csrf_exempt
def instructions(request, moment_id):
    token = request.COOKIES.get('token')
    if not token:
        return login(request)
    recipe_get = requests.get(
        "http://localhost:8000/rest/moments/" + moment_id + "/", auth=JWTAuth(token))
    if recipe_get.status_code >= 400:
        return login(request)
    moment = recipe_get.json()
    if not moment["instructions"]:
        description_get = requests.get(
            "http://localhost:8000/rest/momentfilter/" + moment_id + "/?fields=description", auth=JWTAuth(token))
        if description_get.status_code >= 400:
            return login(request)
        description = description_get.json()
        parameters = {'moment': moment, 'description': description['description']}
    else:
        parameters = {'moment': moment}
    return render(request, 'recipes_site/instructions.html', parameters)


@csrf_exempt
def create_recipe(request):
    token = request.COOKIES.get('token')
    if not token:
        return login(request)
    recipe_get = requests.options(
        "http://localhost:8000/rest/recipes/", auth=JWTAuth(token))
    if recipe_get.status_code >= 400:
        return login(request)
    time_units = [k["display_name"] for k in recipe_get.json()["actions"]["POST"]["time_unit"]["choices"]]
    categories = [k["display_name"] for k in recipe_get.json()["actions"]["POST"]["category"]["choices"]]
    ingredients = [k["display_name"] for k in recipe_get.json()["actions"]["POST"]["moments"]["child"]
    ["children"]["ingredients"]["child"]["children"]["ingredient"]["choices"]]

    form = RecipeForm(time_units,categories)
    moment = MomentForm(ingredients=ingredients)
    return render(request, 'recipes_site/addRecipe.html', {'form': form, 'moment': moment})


@csrf_exempt
def create_quantity(request):
    token = request.COOKIES.get('token')
    if not token:
        return HttpResponseForbidden()
    recipe_get = requests.options(
        "http://localhost:8000/rest/quantities/", auth=JWTAuth(token))
    if recipe_get.status_code >= 400:
        return HttpResponseForbidden()
    ingredients = [k["value"] for k in recipe_get.json()["actions"]["POST"]["ingredient"]["choices"]]
    return render(request, 'recipes_site/addQuantity.html', {'name': 'Quantity', 'form': QuantityForm(ingredients=ingredients)})


@csrf_exempt
def create_moment(request):
    token = request.COOKIES.get('token')
    if not token:
        return HttpResponseForbidden()
    recipe_get = requests.options(
        "http://localhost:8000/rest/moments/", auth=JWTAuth(token))
    if recipe_get.status_code >= 400:
        return HttpResponseForbidden()
    ingredients = [k["value"] for k in recipe_get.json()["actions"]["POST"]["extra_ingredients"]["choices"]]

    return render(request, 'recipes_site/addMoment.html', {'name': 'Moment', 'form': MomentForm(ingredients)})

@csrf_exempt
def login(request):
    return render(request, 'recipes_site/login.html')

recipes_site/templates/recipes_site/addMoment.html
{% load staticfiles %}

<fieldset>
    <legend>{{ name }}</legend>
    {{ form }}
    <div name="{{ name }}"></div>
    <image onclick="addQuantity(this.parentNode)" style="height:30px;cursor:pointer;" src="{% static 'recipes_site/minus-clipart-green-plus-md.png' %}" >Adds</image>
</fieldset>

recipes_site/templates/recipes_site/addQuantity.html
<fieldset>
    <legend>{{ name }}</legend>
    {{ form }}
</fieldset>

recipes_site/templates/recipes_site/addRecipe.html
<!DOCTYPE html>

{% load staticfiles %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Recipe</title>
    <script>
        function addQuantity(parent) {
            "use strict";
            var xhttp = new XMLHttpRequest();
            xhttp.onreadystatechange = function () {
                if (xhttp.readyState === 4 && xhttp.status === 200) {
                    var quantity = parent.querySelectorAll('[name=quantity]')[0];
                    $(quantity).append(xhttp.responseText);
                    var lastChild = quantity.children[quantity.children.length - 1];
                    var ingredient = lastChild.querySelectorAll('[name=ingredient]')[0];
                    $(ingredient).chosen()
                }
                if (xhttp.readyState === 4 && xhttp.status === 403) {
                    window.open("{% url 'recipes_site:login' %}");
                }
            };
            xhttp.open("GET", "{% url 'recipes_site:add-quantity' %}", true);
            xhttp.send();
        }
        function addMoment() {
            "use strict";
            $.ajax( {
                url: "{% url 'recipes_site:add-moment' %}",
                method: "GET",
                error: function(xhr, ajaxOptions, thrownError) {
                    if(xhr.status==403) {
                      window.open("http://localhost:8000{% url 'recipes_site:login' %}", 'window name', 'window settings');
                    }
                },
                success: function(data) {
                    $("#moment").append(data);
                    $("#moment select:last").chosen();
                }
            });
        }

    </script>

    <script src="{% static 'recipes_site/script.js' %}"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>

    <script src="{% static 'recipes_site/chosen.jquery.js' %}"></script>
    <link rel="stylesheet" href="{% static 'recipes_site/chosen.css' %}" />
    <link rel="stylesheet" href="{% static 'recipes_site/style.css' %}" />
    <script>
    $( document ).ready(function() {
        $("#moment select:last").last().chosen();
    });
    </script>
</head>
<body>
<form id="recipe">
    {{ form }}

    <div id="moment">
        <fieldset>
            <legend>Moment</legend>
            {{ moment }}
            <div name="quantity"></div>
            <image onclick="addQuantity(this.parentNode)" style="height:30px;cursor:pointer;" src="{% static 'recipes_site/minus-clipart-green-plus-md.png' %}" />
        </fieldset>
    </div>
    <image onclick="addMoment()" style="height:30px;cursor:pointer;" src="{% static 'recipes_site/minus-clipart-green-plus-md.png' %}" />
    <input type="button" value="Submit" onclick="addRecipe('/rest/recipes/')" />
</form>
</body>
</html>

recipes_site/templates/recipes_site/detail.html
<nav>
    <ul id="menu">
        {% for itr in recipe.moments %}
        <li {% if moment.name == itr.name %}id="selected"{% endif %} onclick="loadDoc('{{ itr.name }}', '{%url 'recipes_site:instructions' itr.id %}')">{{ itr.name }}</li>
        {% endfor %}
    </ul>
</nav>
<section id="content" style="padding:10px">
    {% include 'recipes_site/instructions.html' %}
</section>

recipes_site/templates/recipes_site/index.html
<!DOCTYPE html>

{% load staticfiles %}
<html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'recipes_site/style.css' %}" />
    <script src="https://code.jquery.com/jquery-3.2.1.min.js">
    </script>
    <script src="{% static 'recipes_site/script.js' %}">
    </script>
    <title>Recipe</title>

    <style type="text/css">
        div.inline { float:left; }
        .clearBoth { clear:both; }
    </style>
</head>
<body>
<div class="inline" style="width:30%;max-width:200px">
    {% if recipes %}
    <ul>
        {% for recipe in recipes %}
            <li><a class="menu" onclick="loadRecipe('/recipes/{{ recipe.id }}/', this)">{{ recipe.name }}</a></li>
        {% endfor %}
    </ul>
    {% endif %}
</div>
<div class="inline" style="width:70%;" id="recipe"></div>
</body>
</html>

recipes_site/templates/recipes_site/instructions.html
<table>
    {% for ingredient in moment.ingredients %}

    <tr>
        <td>{{ ingredient.amount }} {{ ingredient.unit }}</td>
        <td>{{ ingredient.ingredient }} {% if ingredient.comment %} ({{ ingredient.comment }}) {%endif%}</td>
    </tr>
    {% endfor %}
    {% if moment.extra_ingredients.all %}
        <tr><td></td><td>
            {{ moment.extra_ingredients | join:", " }}
        </td>

        </tr>
    {% endif %}
</table>
<p>
    {% if moment.instructions %}
    {{ moment.instructions|linebreaks }}
    {% else %}
    {% if recipe %}
    {{ recipe.description|linebreaks }}
    {% else %}
    {{ description|linebreaks }}
    {% endif %}
    {% endif %}
</p>

recipes_site/templates/recipes_site/login.html
<!DOCTYPE html>

{% load staticfiles %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>

    <link rel="stylesheet" href="{% static 'recipes_site/style.css' %}" />
    <script>
        function login() {
            var username = document.getElementById("username").value;
            var password = document.getElementById("password").value;

            var credentials = {};
            credentials.username = username;
            credentials.password = password;
            var json = JSON.stringify(credentials);

            $.ajax( {
                url: '/rest/api-token-auth/',
                contentType: 'application/json',
                data: json,
                method: "POST",
                error: function(data) {
                    $(document.getElementById("errorText")).html(data.responseJSON.non_field_errors[0]);
                },
                success: function(data) {
                    $(document.getElementById("errorText")).html(data.token);
                    Cookies.set("token",data.token);
                    //document.cookie = "token=" + encodeURIComponent(data.token)
                    window.location.replace( {% url 'recipes_site:index' %} );
                }
            });

        }
    </script>
    <script src="{% static 'recipes_site/js.cookie.js' %}"></script>
</head>
<body>
<p>Username:</p><input id="username"/><br />
<p>Password:</p><input type="password" id="password" /><br />
<p id="errorText"></p>
<input type="button" value="Login" onclick="login()"/>
</body>
</html>